# Generated by Django 5.2.9 on 2025-12-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('caption', models.TextField(blank=True)),
                ('category', models.CharField(default='Uncategorized', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
